# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!
import elevsim
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

import dataParsing
import stopwatch


class Ui_MainWindow(object):
    def __init__(self, dialog, parent=None):
        self.ele1_waitingtime=0.0
        self.ele2_waitingtime=0.0
        self.ele3_waitingtime=0.0
        self.ele4_waitingtime=0.0
        self.dialog = dialog

        #self.ui = ui
        print('dialog1 :: ',dialog)
        self.elev = elevsim.Elevsim(dialog)
        #self.thread = GUIThread()
        #self.thread.start()

    def setupUi(self, MainWindow, get):
        self.ui = get

        #self.ui = get
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1282, 710)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.date = QtGui.QLabel(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(21, 20, 32, 16))
        self.date.setObjectName(_fromUtf8("date"))
        self.year = QtGui.QLabel(self.centralwidget)
        self.year.setGeometry(QtCore.QRect(215, 20, 16, 16))
        self.year.setObjectName(_fromUtf8("year"))
        self.month = QtGui.QLabel(self.centralwidget)
        self.month.setGeometry(QtCore.QRect(389, 20, 16, 16))
        self.month.setObjectName(_fromUtf8("month"))
        self.day = QtGui.QLabel(self.centralwidget)
        self.day.setGeometry(QtCore.QRect(563, 20, 16, 16))
        self.day.setObjectName(_fromUtf8("day"))
        self.time = QtGui.QLabel(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(581, 20, 32, 16))
        self.time.setObjectName(_fromUtf8("time"))
        self.hour = QtGui.QLabel(self.centralwidget)
        self.hour.setGeometry(QtCore.QRect(775, 20, 16, 16))
        self.hour.setObjectName(_fromUtf8("hour"))
        self.minute = QtGui.QLabel(self.centralwidget)
        self.minute.setGeometry(QtCore.QRect(949, 20, 16, 16))
        self.minute.setObjectName(_fromUtf8("minute"))
        self.second = QtGui.QLabel(self.centralwidget)
        self.second.setGeometry(QtCore.QRect(1123, 20, 16, 16))
        self.second.setObjectName(_fromUtf8("second"))
        self.yearEdit = QtGui.QLineEdit(self.centralwidget)
        self.yearEdit.setGeometry(QtCore.QRect(59, 21, 150, 20))
        self.yearEdit.setObjectName(_fromUtf8("yearEdit"))
        self.monthEdit = QtGui.QLineEdit(self.centralwidget)
        self.monthEdit.setGeometry(QtCore.QRect(233, 21, 150, 20))
        self.monthEdit.setObjectName(_fromUtf8("monthEdit"))
        self.dayEdit = QtGui.QLineEdit(self.centralwidget)
        self.dayEdit.setGeometry(QtCore.QRect(407, 21, 150, 20))
        self.dayEdit.setObjectName(_fromUtf8("dayEdit"))
        self.hourEdit = QtGui.QLineEdit(self.centralwidget)
        self.hourEdit.setGeometry(QtCore.QRect(619, 21, 150, 20))
        self.hourEdit.setObjectName(_fromUtf8("hourEdit"))
        self.minuteEdit = QtGui.QLineEdit(self.centralwidget)
        self.minuteEdit.setGeometry(QtCore.QRect(793, 21, 150, 20))
        self.minuteEdit.setObjectName(_fromUtf8("minuteEdit"))
        self.secondEdit = QtGui.QLineEdit(self.centralwidget)
        self.secondEdit.setGeometry(QtCore.QRect(967, 21, 150, 20))
        self.secondEdit.setObjectName(_fromUtf8("secondEdit"))
        self.okbutton = QtGui.QPushButton(self.centralwidget)
        self.okbutton.setGeometry(QtCore.QRect(1141, 20, 75, 23))
        self.okbutton.setObjectName(_fromUtf8("okbutton"))
        self.h_12 = QtGui.QFrame(self.centralwidget)
        self.h_12.setGeometry(QtCore.QRect(131, 180, 939, 16))
        self.h_12.setFrameShape(QtGui.QFrame.HLine)
        self.h_12.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_12.setObjectName(_fromUtf8("h_12"))
        self.h_15 = QtGui.QFrame(self.centralwidget)
        self.h_15.setGeometry(QtCore.QRect(131, 90, 939, 16))
        self.h_15.setFrameShape(QtGui.QFrame.HLine)
        self.h_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_15.setObjectName(_fromUtf8("h_15"))
        self.h_14 = QtGui.QFrame(self.centralwidget)
        self.h_14.setGeometry(QtCore.QRect(131, 120, 939, 16))
        self.h_14.setFrameShape(QtGui.QFrame.HLine)
        self.h_14.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_14.setObjectName(_fromUtf8("h_14"))
        self.h_11 = QtGui.QFrame(self.centralwidget)
        self.h_11.setGeometry(QtCore.QRect(131, 210, 939, 16))
        self.h_11.setFrameShape(QtGui.QFrame.HLine)
        self.h_11.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_11.setObjectName(_fromUtf8("h_11"))
        self.h_13 = QtGui.QFrame(self.centralwidget)
        self.h_13.setGeometry(QtCore.QRect(131, 150, 939, 16))
        self.h_13.setFrameShape(QtGui.QFrame.HLine)
        self.h_13.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_13.setObjectName(_fromUtf8("h_13"))
        self.h_10 = QtGui.QFrame(self.centralwidget)
        self.h_10.setGeometry(QtCore.QRect(131, 240, 939, 16))
        self.h_10.setFrameShape(QtGui.QFrame.HLine)
        self.h_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_10.setObjectName(_fromUtf8("h_10"))
        self.h_6 = QtGui.QFrame(self.centralwidget)
        self.h_6.setGeometry(QtCore.QRect(131, 360, 939, 16))
        self.h_6.setFrameShape(QtGui.QFrame.HLine)
        self.h_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_6.setObjectName(_fromUtf8("h_6"))
        self.h_7 = QtGui.QFrame(self.centralwidget)
        self.h_7.setGeometry(QtCore.QRect(131, 330, 939, 16))
        self.h_7.setFrameShape(QtGui.QFrame.HLine)
        self.h_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_7.setObjectName(_fromUtf8("h_7"))
        self.h_8 = QtGui.QFrame(self.centralwidget)
        self.h_8.setGeometry(QtCore.QRect(131, 300, 939, 16))
        self.h_8.setFrameShape(QtGui.QFrame.HLine)
        self.h_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_8.setObjectName(_fromUtf8("h_8"))
        self.h_9 = QtGui.QFrame(self.centralwidget)
        self.h_9.setGeometry(QtCore.QRect(131, 270, 939, 16))
        self.h_9.setFrameShape(QtGui.QFrame.HLine)
        self.h_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_9.setObjectName(_fromUtf8("h_9"))
        self.h_0 = QtGui.QFrame(self.centralwidget)
        self.h_0.setGeometry(QtCore.QRect(131, 540, 939, 16))
        self.h_0.setFrameShape(QtGui.QFrame.HLine)
        self.h_0.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_0.setObjectName(_fromUtf8("h_0"))
        self.h_1 = QtGui.QFrame(self.centralwidget)
        self.h_1.setGeometry(QtCore.QRect(131, 510, 939, 16))
        self.h_1.setFrameShape(QtGui.QFrame.HLine)
        self.h_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_1.setObjectName(_fromUtf8("h_1"))
        self.h_3 = QtGui.QFrame(self.centralwidget)
        self.h_3.setGeometry(QtCore.QRect(131, 450, 939, 16))
        self.h_3.setFrameShape(QtGui.QFrame.HLine)
        self.h_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_3.setObjectName(_fromUtf8("h_3"))
        self.h_4 = QtGui.QFrame(self.centralwidget)
        self.h_4.setGeometry(QtCore.QRect(131, 420, 939, 16))
        self.h_4.setFrameShape(QtGui.QFrame.HLine)
        self.h_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_4.setObjectName(_fromUtf8("h_4"))
        self.h_2 = QtGui.QFrame(self.centralwidget)
        self.h_2.setGeometry(QtCore.QRect(131, 480, 939, 16))
        self.h_2.setFrameShape(QtGui.QFrame.HLine)
        self.h_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_2.setObjectName(_fromUtf8("h_2"))
        self.h_5 = QtGui.QFrame(self.centralwidget)
        self.h_5.setGeometry(QtCore.QRect(131, 390, 939, 16))
        self.h_5.setFrameShape(QtGui.QFrame.HLine)
        self.h_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_5.setObjectName(_fromUtf8("h_5"))
        self.line_21 = QtGui.QFrame(self.centralwidget)
        self.line_21.setGeometry(QtCore.QRect(364, 67, 20, 591))
        self.line_21.setFrameShape(QtGui.QFrame.VLine)
        self.line_21.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_21.setObjectName(_fromUtf8("line_21"))
        self.line_22 = QtGui.QFrame(self.centralwidget)
        self.line_22.setGeometry(QtCore.QRect(120, 66, 20, 591))
        self.line_22.setFrameShape(QtGui.QFrame.VLine)
        self.line_22.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_22.setObjectName(_fromUtf8("line_22"))
        self.line_23 = QtGui.QFrame(self.centralwidget)
        self.line_23.setGeometry(QtCore.QRect(600, 67, 20, 591))
        self.line_23.setFrameShape(QtGui.QFrame.VLine)
        self.line_23.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_23.setObjectName(_fromUtf8("line_23"))
        self.line_24 = QtGui.QFrame(self.centralwidget)
        self.line_24.setGeometry(QtCore.QRect(836, 67, 20, 591))
        self.line_24.setFrameShape(QtGui.QFrame.VLine)
        self.line_24.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_24.setObjectName(_fromUtf8("line_24"))
        self.line_25 = QtGui.QFrame(self.centralwidget)
        self.line_25.setGeometry(QtCore.QRect(1060, 66, 20, 591))
        self.line_25.setFrameShape(QtGui.QFrame.VLine)
        self.line_25.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_25.setObjectName(_fromUtf8("line_25"))
        self.car1 = QtGui.QPushButton(self.centralwidget)
        self.car1.setGeometry(QtCore.QRect(140, 518, 21, 31))
        self.car1.setObjectName(_fromUtf8("car1"))
        self.h_16 = QtGui.QFrame(self.centralwidget)
        self.h_16.setGeometry(QtCore.QRect(130, 58, 939, 16))
        self.h_16.setFrameShape(QtGui.QFrame.HLine)
        self.h_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.h_16.setObjectName(_fromUtf8("h_16"))
        self.car2 = QtGui.QPushButton(self.centralwidget)
        self.car2.setGeometry(QtCore.QRect(380, 518, 21, 31))
        self.car2.setObjectName(_fromUtf8("car2"))
        self.car3 = QtGui.QPushButton(self.centralwidget)
        self.car3.setGeometry(QtCore.QRect(620, 518, 21, 31))
        self.car3.setObjectName(_fromUtf8("car3"))
        self.car4 = QtGui.QPushButton(self.centralwidget)
        self.car4.setGeometry(QtCore.QRect(850, 518, 21, 31))
        self.car4.setObjectName(_fromUtf8("car4"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-100, 40, 34, 4))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.line_17 = QtGui.QFrame(self.widget)
        self.line_17.setFrameShape(QtGui.QFrame.VLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.horizontalLayout_2.addWidget(self.line_17)
        self.line_18 = QtGui.QFrame(self.widget)
        self.line_18.setFrameShape(QtGui.QFrame.VLine)
        self.line_18.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_18.setObjectName(_fromUtf8("line_18"))
        self.horizontalLayout_2.addWidget(self.line_18)
        self.line_19 = QtGui.QFrame(self.widget)
        self.line_19.setFrameShape(QtGui.QFrame.VLine)
        self.line_19.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_19.setObjectName(_fromUtf8("line_19"))
        self.horizontalLayout_2.addWidget(self.line_19)
        self.line_20 = QtGui.QFrame(self.widget)
        self.line_20.setFrameShape(QtGui.QFrame.VLine)
        self.line_20.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_20.setObjectName(_fromUtf8("line_20"))
        self.horizontalLayout_2.addWidget(self.line_20)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.widget1 = QtGui.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(140, 558, 221, 101))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.widget1)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget1)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.car1WaitingTime = QtGui.QLabel(self.widget1)
        self.car1WaitingTime.setObjectName(_fromUtf8("car1WaitingTime"))
        self.gridLayout_3.addWidget(self.car1WaitingTime, 1, 2, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.car1StartFloor = QtGui.QLabel(self.widget1)
        self.car1StartFloor.setObjectName(_fromUtf8("car1StartFloor"))
        self.gridLayout_3.addWidget(self.car1StartFloor, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget1)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 3, 0, 1, 1)
        self.car1Destination = QtGui.QLabel(self.widget1)
        self.car1Destination.setObjectName(_fromUtf8("car1Destination"))
        self.gridLayout_3.addWidget(self.car1Destination, 3, 2, 1, 1)
        self.widget2 = QtGui.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(380, 558, 221, 101))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.widget2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.widget2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.car2WaitingTime = QtGui.QLabel(self.widget2)
        self.car2WaitingTime.setObjectName(_fromUtf8("car2WaitingTime"))
        self.gridLayout_4.addWidget(self.car2WaitingTime, 1, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_4.addWidget(self.label_10, 2, 0, 1, 1)
        self.car2StartFloor = QtGui.QLabel(self.widget2)
        self.car2StartFloor.setObjectName(_fromUtf8("car2StartFloor"))
        self.gridLayout_4.addWidget(self.car2StartFloor, 2, 2, 1, 1)
        self.label_16 = QtGui.QLabel(self.widget2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 3, 0, 1, 1)
        self.car2Destination = QtGui.QLabel(self.widget2)
        self.car2Destination.setObjectName(_fromUtf8("car2Destination"))
        self.gridLayout_4.addWidget(self.car2Destination, 3, 2, 1, 1)
        self.widget3 = QtGui.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(620, 558, 211, 101))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.widget3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_3 = QtGui.QLabel(self.widget3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_5.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.widget3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.car3WaitingTime = QtGui.QLabel(self.widget3)
        self.car3WaitingTime.setObjectName(_fromUtf8("car3WaitingTime"))
        self.gridLayout_5.addWidget(self.car3WaitingTime, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 2, 0, 1, 1)
        self.car2StartFloor_2 = QtGui.QLabel(self.widget3)
        self.car2StartFloor_2.setObjectName(_fromUtf8("car2StartFloor_2"))
        self.gridLayout_5.addWidget(self.car2StartFloor_2, 2, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.widget3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 3, 0, 1, 1)
        self.car3Destination = QtGui.QLabel(self.widget3)
        self.car3Destination.setObjectName(_fromUtf8("car3Destination"))
        self.gridLayout_5.addWidget(self.car3Destination, 3, 2, 1, 1)
        self.widget4 = QtGui.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(850, 558, 211, 101))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_4 = QtGui.QLabel(self.widget4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.widget4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.car4WaitingTime = QtGui.QLabel(self.widget4)
        self.car4WaitingTime.setObjectName(_fromUtf8("car4WaitingTime"))
        self.gridLayout_6.addWidget(self.car4WaitingTime, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 2, 0, 1, 1)
        self.car4StartFloor = QtGui.QLabel(self.widget4)
        self.car4StartFloor.setObjectName(_fromUtf8("car4StartFloor"))
        self.gridLayout_6.addWidget(self.car4StartFloor, 2, 2, 1, 1)
        self.label_14 = QtGui.QLabel(self.widget4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_6.addWidget(self.label_14, 3, 0, 1, 1)
        self.car4Destination = QtGui.QLabel(self.widget4)
        self.car4Destination.setObjectName(_fromUtf8("car4Destination"))
        self.gridLayout_6.addWidget(self.car4Destination, 3, 2, 1, 1)
        self.date.raise_()
        self.year.raise_()
        self.month.raise_()
        self.day.raise_()
        self.time.raise_()
        self.hour.raise_()
        self.minute.raise_()
        self.second.raise_()
        self.yearEdit.raise_()
        self.monthEdit.raise_()
        self.dayEdit.raise_()
        self.hourEdit.raise_()
        self.minuteEdit.raise_()
        self.secondEdit.raise_()
        self.okbutton.raise_()
        self.h_12.raise_()
        self.h_15.raise_()
        self.h_14.raise_()
        self.h_11.raise_()
        self.h_13.raise_()
        self.h_10.raise_()
        self.h_6.raise_()
        self.h_7.raise_()
        self.h_8.raise_()
        self.h_9.raise_()
        self.h_0.raise_()
        self.h_1.raise_()
        self.h_3.raise_()
        self.h_4.raise_()
        self.h_2.raise_()
        self.h_5.raise_()
        self.line_17.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_20.raise_()
        self.line_17.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_20.raise_()
        self.line_17.raise_()
        self.line_18.raise_()
        self.line_19.raise_()
        self.line_20.raise_()
        self.line_21.raise_()
        self.line_22.raise_()
        self.line_23.raise_()
        self.line_24.raise_()
        self.line_21.raise_()
        self.line_22.raise_()
        self.line_23.raise_()
        self.line_24.raise_()
        self.line_25.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.label_13.raise_()
        self.label_14.raise_()
        self.label_15.raise_()
        self.label_16.raise_()
        self.car1WaitingTime.raise_()
        self.car1StartFloor.raise_()
        self.car1Destination.raise_()
        self.car2WaitingTime.raise_()
        self.car2StartFloor.raise_()
        self.car2Destination.raise_()
        self.car3WaitingTime.raise_()
        self.car2StartFloor_2.raise_()
        self.car3Destination.raise_()
        self.car4WaitingTime.raise_()
        self.car4StartFloor.raise_()
        self.car4Destination.raise_()
        self.car4StartFloor.raise_()
        self.car4WaitingTime.raise_()
        self.car1.raise_()
        self.h_16.raise_()
        self.car2.raise_()
        self.car3.raise_()
        self.car4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1282, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.okbutton, QtCore.SIGNAL(_fromUtf8("clicked()")), self.ok)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.date.setText(_translate("MainWindow", "날짜: ", None))
        self.year.setText(_translate("MainWindow", "년", None))
        self.month.setText(_translate("MainWindow", "월", None))
        self.day.setText(_translate("MainWindow", "일", None))
        self.time.setText(_translate("MainWindow", "시간: ", None))
        self.hour.setText(_translate("MainWindow", "시", None))
        self.minute.setText(_translate("MainWindow", "분", None))
        self.second.setText(_translate("MainWindow", "초", None))
        self.okbutton.setText(_translate("MainWindow", "ok", None))
        self.car1.setText(_translate("MainWindow", "▲", None))
        self.car2.setText(_translate("MainWindow", "▲", None))
        self.car3.setText(_translate("MainWindow", "▲", None))
        self.car4.setText(_translate("MainWindow", "▲", None))
        self.label.setText(_translate("MainWindow", "car1", None))
        self.label_5.setText(_translate("MainWindow", "waiting time", None))
        self.car1WaitingTime.setText(_translate("MainWindow", "0", None))
        self.label_9.setText(_translate("MainWindow", "start floor", None))
        self.car1StartFloor.setText(_translate("MainWindow", "0", None))
        self.label_13.setText(_translate("MainWindow", "destination", None))
        self.car1Destination.setText(_translate("MainWindow", "0", None))
        self.label_2.setText(_translate("MainWindow", "car2", None))
        self.label_6.setText(_translate("MainWindow", "waiting time", None))
        self.car2WaitingTime.setText(_translate("MainWindow", "0", None))
        self.label_10.setText(_translate("MainWindow", "start floor", None))
        self.car2StartFloor.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "destination", None))
        self.car2Destination.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "car3", None))
        self.label_7.setText(_translate("MainWindow", "waiting time", None))
        self.car3WaitingTime.setText(_translate("MainWindow", "0", None))
        self.label_11.setText(_translate("MainWindow", "start floor", None))
        self.car2StartFloor_2.setText(_translate("MainWindow", "0", None))
        self.label_15.setText(_translate("MainWindow", "destination", None))
        self.car3Destination.setText(_translate("MainWindow", "0", None))
        self.label_4.setText(_translate("MainWindow", "car4", None))
        self.label_8.setText(_translate("MainWindow", "waiting time", None))
        self.car4WaitingTime.setText(_translate("MainWindow", "0", None))
        self.label_12.setText(_translate("MainWindow", "start floor", None))
        self.car4StartFloor.setText(_translate("MainWindow", "0", None))
        self.label_14.setText(_translate("MainWindow", "destination", None))
        self.car4Destination.setText(_translate("MainWindow", "0", None))


    def ok(self):


        data = dataParsing.generateData(self.yearEdit.text(),
                                        self.monthEdit.text(),self.dayEdit.text(),self.hourEdit.text(),
                                        self.minuteEdit.text(),self.secondEdit.text())
        self.dialog.timer[0] = int(self.hourEdit.text())
        self.dialog.timer[1] = int(self.minuteEdit.text())
        self.dialog.timer[2] = int(self.secondEdit.text())-1

        watch = stopwatch.StopWatch(self.dialog)
        watch.start()

        self.elev.run(data, self.ui)




    def up(self, eleNum):
        if eleNum == 1:
            self.car1.move(self.car1.x(),self.car1.y()-self.car1.height())
        if eleNum == 2:
            self.car2.move(self.car2.x(),self.car2.y()-self.car2.height())
        if eleNum == 3:
            self.car3.move(self.car3.x(),self.car3.y()-self.car3.height())
        if eleNum == 4:
            self.car4.move(self.car4.x(),self.car4.y()-self.car4.height())

    def down(self,eleNum):
        if eleNum == 1:
            self.car1.move(self.car1.x(),self.car1.y()+self.car1.height())
        if eleNum == 2:
            self.car2.move(self.car2.x(),self.car2.y()+self.car2.height())
        if eleNum == 3:
            self.car3.move(self.car3.x(),self.car3.y()+self.car3.height())
        if eleNum == 4:
            self.car4.move(self.car4.x(),self.car4.y()+self.car4.height())

    def toggle(self):

        self.car1.setEnabled(True)
        self.car2.setEnabled(True)
        self.car3.setEnabled(True)
        self.car4.setEnabled(True)







